"""Pre-seeded demo data for ProductionPulse.
Contains comprehensive production datasets for original feature films (Mind Heist, Cyber Horizon)
allowing judges to immediately explore deep production analytics with zero setup.
"""
from typing import Dict, Any, List
import uuid

DEMO_PROJECTS: Dict[str, Dict[str, Any]] = {
    "mindheist": {
        "id": "e4a2c710-5321-4f1a-b672-000000000001",
        "name": "Mind Heist",
        "script_title": "MIND HEIST - Written by Julian Vance",
        "total_scenes": 15,
        "total_pages": 42.5,
        "estimated_budget_usd": 160000000.0,
        "estimated_shoot_days": 38.0,
        "complexity_score": 9,
        "status": "scheduled",
        "scenes": [
            {
                "scene_number": 1,
                "heading": "EXT. JAPANESE FORTRESS / OCEAN - NIGHT",
                "location": "COASTAL FORTRESS",
                "int_ext": "exterior",
                "time_of_day": "night",
                "description": "Waves crash against rocks. A washed-up ETHAN VANCE is found unconscious by armed security guards on a rocky coastline.",
                "characters": ["ETHAN VANCE", "SECURITY GUARD", "KENJI TAKAHASHI"],
                "props": ["Pewter Totem", "Silenced Pistol", "Wet Suit"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 8,
                "estimated_shoot_hours": 8.0,
                "page_count": 2.5,
                "mood": "mysterious",
                "complexity_score": 8
            },
            {
                "scene_number": 2,
                "heading": "INT. DINING ROOM, COASTAL FORTRESS - NIGHT",
                "location": "COASTAL FORTRESS",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Elderly KENJI sits across from ETHAN at an ornate dining table eating dinner. Kenji recognizes the spinning pewter totem.",
                "characters": ["ETHAN VANCE", "KENJI TAKAHASHI", "MARCUS COLE"],
                "props": ["Pewter Totem", "Silver Dining Set", "Antique Tea Cup"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 2,
                "estimated_shoot_hours": 4.0,
                "page_count": 2.0,
                "mood": "tense",
                "complexity_score": 4
            },
            {
                "scene_number": 3,
                "heading": "INT. APARTMENT / EXTRACTION SUITE - NIGHT",
                "location": "TAKAHASHI APARTMENT",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Young KENJI wakes up to find ETHAN dangling from a rope outside his window trying to break into the secret safe.",
                "characters": ["ETHAN VANCE", "KENJI TAKAHASHI", "MARCUS COLE", "CLAIRE VANCE"],
                "props": ["Rappelling Harness", "Burner Phone", "Biometric Safe Cracker"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 0,
                "estimated_shoot_hours": 6.0,
                "page_count": 3.0,
                "mood": "kinetic",
                "complexity_score": 7
            },
            {
                "scene_number": 4,
                "heading": "EXT. PARIS BOULEVARD / CAFE - DAY",
                "location": "PARIS CAFE",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Ethan explains dream architecture to MAYA LIN. The street begins to fold 90 degrees upwards in a gravity-defying arch.",
                "characters": ["ETHAN VANCE", "MAYA LIN"],
                "props": ["Espresso Cups", "Architect Sketchbook", "Folding Street VFX"],
                "vfx_required": True,
                "stunts_required": False,
                "extras_count": 20,
                "estimated_shoot_hours": 10.0,
                "page_count": 3.5,
                "mood": "surreal",
                "complexity_score": 9
            },
            {
                "scene_number": 5,
                "heading": "INT. ARCHITECTURE LAB / MAZE DEMO - DAY",
                "location": "MAYA'S LAB",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Maya designs complex recursive spatial labyrinths on transparent acrylic drafting boards for Ethan's upcoming operation.",
                "characters": ["MAYA LIN", "ETHAN VANCE"],
                "props": ["Acrylic Drafting Tables", "Compass Rulers", "Graphite Models"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 4.0,
                "page_count": 2.0,
                "mood": "intellectual",
                "complexity_score": 3
            },
            {
                "scene_number": 6,
                "heading": "EXT. MOMBASA MARKET BAZAAR - DAY",
                "location": "MOMBASA BAZAAR",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Cobalt operatives corner Ethan. A high-stakes foot chase ensues through crowded alleyways, squeezing between closing walls.",
                "characters": ["ETHAN VANCE", "DEVON REED", "COBALT OPERATIVES"],
                "props": ["Concealed Pistols", "Fruit Carts", "Motorcycles"],
                "vfx_required": False,
                "stunts_required": True,
                "extras_count": 80,
                "estimated_shoot_hours": 12.0,
                "page_count": 4.0,
                "mood": "thrilling",
                "complexity_score": 8
            },
            {
                "scene_number": 7,
                "heading": "INT. PHARMACY LAB / BASEMENT - DAY",
                "location": "DR. MALIK'S LAB",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Dr. Malik demonstrates compound sedatives on test subjects. Ethan tests the compound and experiences deep inner-mind clarity.",
                "characters": ["DR. TARIQ MALIK", "ETHAN VANCE", "DEVON REED"],
                "props": ["Chemical Distillation Glassware", "PASIV Automated Infusion Unit", "Sedative Vials"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 12,
                "estimated_shoot_hours": 6.0,
                "page_count": 3.0,
                "mood": "clinical",
                "complexity_score": 4
            },
            {
                "scene_number": 8,
                "heading": "INT. BOEING 747 FIRST CLASS CABIN - DAY",
                "location": "FIRST CLASS CABIN",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "10-hour flight to Los Angeles. The team initiates the multi-layered neural sync on unsuspecting heir DAMIAN STERLING.",
                "characters": ["ETHAN VANCE", "DAMIAN STERLING", "MARCUS COLE", "MAYA LIN", "DEVON REED", "KENJI TAKAHASHI", "DR. TARIQ MALIK"],
                "props": ["PASIV Silver Briefcase", "IV Tubing", "Champagne Glasses"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 6,
                "estimated_shoot_hours": 6.0,
                "page_count": 3.0,
                "mood": "suspenseful",
                "complexity_score": 5
            },
            {
                "scene_number": 9,
                "heading": "EXT. RAIN-SWEPT CITY STREETS - DAY",
                "location": "DREAM CITY - LEVEL 1",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Heavy downpour. A massive freight locomotive plows right down the center of the asphalt street, crashing through yellow cabs.",
                "characters": ["ETHAN VANCE", "MAYA LIN", "MARCUS COLE", "STERLING SECURITY SUB-CONSCIOUS"],
                "props": ["Freight Train Engine", "Taxi Cabs", "Assault Rifles", "Rain FX Rigs"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 50,
                "estimated_shoot_hours": 12.0,
                "page_count": 4.5,
                "mood": "chaotic",
                "complexity_score": 10
            },
            {
                "scene_number": 10,
                "heading": "INT. VAN IN SLOW MOTION / HIGHWAY - DAY",
                "location": "HIGHWAY BRIDGE",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Dr. Malik drives the white Econoline van off the suspension bridge while the entire team floats asleep inside in zero gravity.",
                "characters": ["DR. TARIQ MALIK", "ETHAN VANCE", "MARCUS COLE", "MAYA LIN", "KENJI TAKAHASHI", "DAMIAN STERLING", "DEVON REED"],
                "props": ["Econoline Van", "Gimbal Rig", "Headphones"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 0,
                "estimated_shoot_hours": 10.0,
                "page_count": 2.5,
                "mood": "suspended",
                "complexity_score": 9
            },
            {
                "scene_number": 11,
                "heading": "INT. HOTEL CORRIDOR (ZERO GRAVITY) - NIGHT",
                "location": "HOTEL CORRIDOR - LEVEL 2",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "The hotel hallway rotates 360 degrees. Marcus engages in a hand-to-hand fight against militarized sub-conscious projections on walls and ceiling.",
                "characters": ["MARCUS COLE", "SECURITY PROJECTIONS"],
                "props": ["Centrifuge Rotating Gimbal Hallway", "Grappling Ropes", "Elevator Explosives"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 4,
                "estimated_shoot_hours": 14.0,
                "page_count": 4.0,
                "mood": "kinetic",
                "complexity_score": 10
            },
            {
                "scene_number": 12,
                "heading": "EXT. SNOW FORTRESS COMPLEX - DAY",
                "location": "SNOW FORTRESS - LEVEL 3",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Devon on skis leads an assault team in white winter camouflage against a brutalist mountain fortress amidst a blizzard.",
                "characters": ["DEVON REED", "KENJI TAKAHASHI", "DAMIAN STERLING", "FORTRESS GUARDS"],
                "props": ["Snowmobiles", "Ski Gear", "Rocket Launchers", "C4 Detonators"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 30,
                "estimated_shoot_hours": 12.0,
                "page_count": 3.5,
                "mood": "explosive",
                "complexity_score": 9
            },
            {
                "scene_number": 13,
                "heading": "EXT. COLLAPSING CITY / SHORELINE (LIMBO) - DAY",
                "location": "LIMBO METROPOLIS",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Decaying modernist skyscrapers collapse into rolling ocean waves. Ethan and Maya wash ashore in the lowest level of subconsciousness.",
                "characters": ["ETHAN VANCE", "MAYA LIN"],
                "props": ["Crumbled Concrete Columns", "Sand Dunes", "Pocket Watch"],
                "vfx_required": True,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 8.0,
                "page_count": 3.0,
                "mood": "haunting",
                "complexity_score": 8
            },
            {
                "scene_number": 14,
                "heading": "INT. MEMORY APARTMENT (LIMBO) - NIGHT",
                "location": "VANCE RESIDENCE - LIMBO",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Ethan confronts the shadow memory of Claire to let her go and rescue Kenji before the neural kick runs out of time.",
                "characters": ["ETHAN VANCE", "CLAIRE VANCE", "MAYA LIN"],
                "props": ["Kitchen Knife", "Dollhouse Safe", "Spinning Totem"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 5.0,
                "page_count": 2.5,
                "mood": "emotional",
                "complexity_score": 4
            },
            {
                "scene_number": 15,
                "heading": "INT. VANCE HOME - DAY",
                "location": "VANCE HOME",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Ethan returns home, spins his pewter totem on the wooden dining table, and runs outside to embrace his children. The totem spins continuously.",
                "characters": ["ETHAN VANCE", "PHILLIPA", "JAMES", "PROFESSOR MILES"],
                "props": ["Pewter Totem", "Children Toys", "Luggage Bag"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 3.0,
                "page_count": 1.5,
                "mood": "poignant",
                "complexity_score": 2
            }
        ],
        "characters": [
            {"name": "ETHAN VANCE", "description": "The Extractor and team leader", "scene_appearances": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 15], "total_scenes": 13, "is_lead": True, "estimated_cost_per_day": 25000},
            {"name": "MARCUS COLE", "description": "The Point Man managing logistics", "scene_appearances": [2, 3, 8, 9, 10, 11], "total_scenes": 6, "is_lead": True, "estimated_cost_per_day": 12000},
            {"name": "MAYA LIN", "description": "The Architect designing spatial labyrinths", "scene_appearances": [4, 5, 8, 9, 10, 13, 14], "total_scenes": 7, "is_lead": True, "estimated_cost_per_day": 10000},
            {"name": "DEVON REED", "description": "The Forger identity specialist", "scene_appearances": [6, 7, 8, 10, 12], "total_scenes": 5, "is_lead": False, "estimated_cost_per_day": 8500},
            {"name": "KENJI TAKAHASHI", "description": "The Energy magnate client", "scene_appearances": [1, 2, 3, 7, 8, 10, 12], "total_scenes": 7, "is_lead": False, "estimated_cost_per_day": 9000},
            {"name": "DR. TARIQ MALIK", "description": "The Chemist compounding sedative vectors", "scene_appearances": [7, 8, 9, 10], "total_scenes": 4, "is_lead": False, "estimated_cost_per_day": 5000},
            {"name": "CLAIRE VANCE", "description": "The Shade projection haunting Ethan", "scene_appearances": [3, 13, 14], "total_scenes": 3, "is_lead": False, "estimated_cost_per_day": 14000},
            {"name": "DAMIAN STERLING", "description": "The Mark heir to multinational empire", "scene_appearances": [8, 9, 10, 12], "total_scenes": 4, "is_lead": False, "estimated_cost_per_day": 7500}
        ],
        "locations": [
            {"name": "COASTAL FORTRESS", "scene_count": 2, "int_ext": "both", "time_of_day": "night", "estimated_shoot_days": 3.0, "complexity_score": 7, "permit_required": True},
            {"name": "PARIS CAFE", "scene_count": 1, "int_ext": "exterior", "time_of_day": "day", "estimated_shoot_days": 2.5, "complexity_score": 9, "permit_required": True},
            {"name": "MOMBASA BAZAAR", "scene_count": 1, "int_ext": "exterior", "time_of_day": "day", "estimated_shoot_days": 2.0, "complexity_score": 8, "permit_required": True},
            {"name": "HOTEL CORRIDOR - LEVEL 2", "scene_count": 1, "int_ext": "interior", "time_of_day": "night", "estimated_shoot_days": 6.0, "complexity_score": 10, "permit_required": False},
            {"name": "SNOW FORTRESS - LEVEL 3", "scene_count": 1, "int_ext": "exterior", "time_of_day": "day", "estimated_shoot_days": 5.0, "complexity_score": 9, "permit_required": True},
            {"name": "DREAM CITY - LEVEL 1", "scene_count": 2, "int_ext": "exterior", "time_of_day": "day", "estimated_shoot_days": 4.5, "complexity_score": 10, "permit_required": True}
        ],
        "budget_items": [
            {"category": "Cast & Talent", "item_name": "Lead Cast (Ethan, Marcus, Maya)", "quantity": 38, "unit_cost_usd": 47000, "total_cost_usd": 1786000, "scene_numbers": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], "notes": "SAG-AFTRA Schedule F terms"},
            {"category": "Special Effects (SFX)", "item_name": "Centrifuge Rotating Corridor Gimbal", "quantity": 1, "unit_cost_usd": 3200000, "total_cost_usd": 3200000, "scene_numbers": [11], "notes": "Full-size custom engineering steel ring"},
            {"category": "Visual Effects (VFX)", "item_name": "Paris Folding City & Limbo Collapse Shots", "quantity": 340, "unit_cost_usd": 85000, "total_cost_usd": 28900000, "scene_numbers": [4, 9, 13], "notes": "High-end visual effects pipeline"},
            {"category": "Stunts & Safety", "item_name": "Precision Driving, Ski Assault & Zero-G Wirework", "quantity": 18, "unit_cost_usd": 65000, "total_cost_usd": 1170000, "scene_numbers": [1, 3, 6, 9, 10, 11, 12], "notes": "Hazard insurance included"},
            {"category": "Locations & Permits", "item_name": "Paris, Mombasa, Calgary & Studio Stage Leases", "quantity": 4, "unit_cost_usd": 650000, "total_cost_usd": 2600000, "scene_numbers": [1, 4, 6, 12], "notes": "International location logistics"}
        ],
        "schedule_items": [
            {"day_number": 1, "scene_numbers": [1, 2], "location": "COASTAL FORTRESS", "int_ext": "both", "time_of_day": "night", "estimated_hours": 12.0, "crew_size": 85, "notes": "Night shoot on location with ocean wave SFX rigs"},
            {"day_number": 2, "scene_numbers": [3], "location": "TAKAHASHI APARTMENT", "int_ext": "interior", "time_of_day": "night", "estimated_hours": 10.0, "crew_size": 60, "notes": "Rope stunts and safe cracking dialogue"},
            {"day_number": 3, "scene_numbers": [4, 5], "location": "PARIS CAFE & LAB", "int_ext": "both", "time_of_day": "day", "estimated_hours": 12.0, "crew_size": 120, "notes": "Paris street shutdown with exploding debris rigs"},
            {"day_number": 4, "scene_numbers": [6], "location": "MOMBASA BAZAAR", "int_ext": "exterior", "time_of_day": "day", "estimated_hours": 11.0, "crew_size": 95, "notes": "Foot chase through 80 extras"},
            {"day_number": 5, "scene_numbers": [7, 8], "location": "DR. MALIK LAB & 747", "int_ext": "interior", "time_of_day": "day", "estimated_hours": 10.5, "crew_size": 55, "notes": "Dialogue and PASIV setup"},
            {"day_number": 6, "scene_numbers": [9, 10], "location": "DREAM CITY - LEVEL 1", "int_ext": "both", "time_of_day": "day", "estimated_hours": 14.0, "crew_size": 140, "notes": "Practical freight train on tractor frame in rain"},
            {"day_number": 7, "scene_numbers": [11], "location": "HOTEL CORRIDOR", "int_ext": "interior", "time_of_day": "night", "estimated_hours": 14.0, "crew_size": 75, "notes": "Centrifuge rotating rig stunt choreography"},
            {"day_number": 8, "scene_numbers": [12], "location": "SNOW FORTRESS", "int_ext": "exterior", "time_of_day": "day", "estimated_hours": 12.0, "crew_size": 110, "notes": "Mountain exterior practical pyrotechnics"}
        ]
    },
    "cyberhorizon": {
        "id": "e4a2c710-5321-4f1a-b672-000000000002",
        "name": "Cyber Horizon",
        "script_title": "CYBER HORIZON - Written by Elena Rostova",
        "total_scenes": 12,
        "total_pages": 36.0,
        "estimated_budget_usd": 63000000.0,
        "estimated_shoot_days": 32.0,
        "complexity_score": 10,
        "status": "scheduled",
        "scenes": [
            {
                "scene_number": 1,
                "heading": "INT. SECTOR 7 HAVEN HOTEL - NIGHT",
                "location": "HAVEN HOTEL ROOM 303",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Valerie is cornered by enforcement units. She executes the 360-degree floating crane kick against a tactical officer.",
                "characters": ["VALERIE", "LIEUTENANT", "AGENT CIPHER"],
                "props": ["Rotary Terminal", "Flashlights", "Energy Pistol", "High-Speed Array"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 8,
                "estimated_shoot_hours": 14.0,
                "page_count": 3.0,
                "mood": "cyberpunk",
                "complexity_score": 10
            },
            {
                "scene_number": 2,
                "heading": "INT. KAI'S APARTMENT - NIGHT",
                "location": "KAI APARTMENT 101",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Kai sleeps in front of multiple holographic terminals. Text appears: 'Wake up, Kai... The Grid is listening.'",
                "characters": ["KAI", "SYNTH DEALER", "RUNNER"],
                "props": ["Holo-Monitors", "Encrypted Data Shards", "Neural Interface Jack"],
                "vfx_required": False,
                "stunts_required": False,
                "extras_count": 3,
                "estimated_shoot_hours": 4.0,
                "page_count": 2.0,
                "mood": "alienated",
                "complexity_score": 2
            },
            {
                "scene_number": 3,
                "heading": "INT. MEGA-CORP CUBICLE COMPLEX - DAY",
                "location": "OMNICORP TOWER",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Orion contacts Kai via encrypted transceiver, directing him to evade three Cipher units advancing through the cubicle maze.",
                "characters": ["KAI", "AGENT CIPHER", "ORION (V.O.)"],
                "props": ["Neural Comm-Link", "Scaffolding Plank", "Glass Partitions"],
                "vfx_required": False,
                "stunts_required": True,
                "extras_count": 40,
                "estimated_shoot_hours": 8.0,
                "page_count": 3.5,
                "mood": "paranoid",
                "complexity_score": 6
            },
            {
                "scene_number": 4,
                "heading": "INT. CYBERNETIC INTERROGATION CELL - DAY",
                "location": "FEDERAL ARCHIVE",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Agent Cipher overrides Kai's vocal synth and implants an organic-metallic tracker probe through his neural cortex.",
                "characters": ["KAI", "AGENT CIPHER", "AGENT VEX", "AGENT FLINT"],
                "props": ["Two-Way Mirror", "Metallic Bio-Probe", "Restraint Chair"],
                "vfx_required": True,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 6.0,
                "page_count": 2.5,
                "mood": "horrific",
                "complexity_score": 7
            },
            {
                "scene_number": 5,
                "heading": "INT. SANCTUARY SAFE-HOUSE - NIGHT",
                "location": "SANCTUARY SAFE-HOUSE",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Orion offers Kai the choice between the blue code (simulation) and red code (physical reality). Kai swallows the red key.",
                "characters": ["KAI", "ORION", "VALERIE"],
                "props": ["Red Code Capsule", "Blue Code Capsule", "Liquid Mirror Rig"],
                "vfx_required": True,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 6.0,
                "page_count": 3.0,
                "mood": "philosophical",
                "complexity_score": 6
            },
            {
                "scene_number": 6,
                "heading": "INT. VIRTUAL DOJO CONSTRUCT - SIMULATED DAY",
                "location": "DOJO SIMULATION",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Orion tests Kai's martial arts skills in a virtual sparring dojo. High-speed wire martial arts with structural damage.",
                "characters": ["KAI", "ORION", "OPERATOR JAX"],
                "props": ["Tatami Sparring Mats", "Japanese Shoji Screens", "Neural Feed Console"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 0,
                "estimated_shoot_hours": 14.0,
                "page_count": 4.0,
                "mood": "exhilarating",
                "complexity_score": 10
            },
            {
                "scene_number": 7,
                "heading": "INT. GOVERNMENT ATRIUM LOBBY - DAY",
                "location": "GOVERNMENT ATRIUM",
                "int_ext": "interior",
                "time_of_day": "day",
                "description": "Kai and Valerie enter in leather trench coats. Heavy tactical fire shatters marble pillars in explosive slow motion.",
                "characters": ["KAI", "VALERIE", "SECURITY SQUAD", "TACTICAL UNIT"],
                "props": ["Tactical Submachine Guns", "Heavy Shotguns", "Exploding Column Rigs"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 25,
                "estimated_shoot_hours": 16.0,
                "page_count": 5.0,
                "mood": "kinetic",
                "complexity_score": 10
            },
            {
                "scene_number": 8,
                "heading": "EXT. SKYSCRAPER HELIPAD - DAY",
                "location": "ROOFTOP HELIPAD",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Kai evades incoming fire with iconic bullet-time reflex curves. Valerie neutralizes an agent point blank.",
                "characters": ["KAI", "VALERIE", "AGENT VEX"],
                "props": ["Heavy Sidearm", "Tactical Gunship", "Bullet-Time Green Screen Rig"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 0,
                "estimated_shoot_hours": 12.0,
                "page_count": 3.0,
                "mood": "legendary",
                "complexity_score": 10
            },
            {
                "scene_number": 9,
                "heading": "INT. SUBWAY TUNNEL PLATFORM - NIGHT",
                "location": "SUBWAY PLATFORM",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Kai stands his ground against Agent Cipher on the subterranean train tracks in a brutal combat showdown.",
                "characters": ["KAI", "AGENT CIPHER"],
                "props": ["High-Speed Train", "Concrete Wall Fracture FX", "Tinted Glasses"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 0,
                "estimated_shoot_hours": 12.0,
                "page_count": 4.0,
                "mood": "gritty",
                "complexity_score": 9
            },
            {
                "scene_number": 10,
                "heading": "INT. HOVER-SHIP COMMAND DECK - REALITY NIGHT",
                "location": "REBEL SHIP HORIZON",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Hunter-killer drones breach the ship hull with plasma cutters while Operator Jax arms the EMP overload.",
                "characters": ["ORION", "VALERIE", "OPERATOR JAX"],
                "props": ["EMP Capacitors", "Neural Jack Ports", "Plasma Tentacle Rigs"],
                "vfx_required": True,
                "stunts_required": False,
                "extras_count": 0,
                "estimated_shoot_hours": 6.0,
                "page_count": 2.0,
                "mood": "apocalyptic",
                "complexity_score": 7
            },
            {
                "scene_number": 11,
                "heading": "INT. APARTMENT 303 (CLIMAX) - NIGHT",
                "location": "ROOM 303",
                "int_ext": "interior",
                "time_of_day": "night",
                "description": "Cipher strikes down Kai. In the physical realm, Valerie kisses Kai. Kai ascends, stopping hypersonic projectiles in mid-air.",
                "characters": ["KAI", "AGENT CIPHER", "VALERIE"],
                "props": ["Suspended Projectiles FX", "Analog Terminal Receiver"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 0,
                "estimated_shoot_hours": 8.0,
                "page_count": 2.5,
                "mood": "transcendent",
                "complexity_score": 9
            },
            {
                "scene_number": 12,
                "heading": "EXT. METROPOLIS PUBLIC TERMINAL - DAY",
                "location": "DOWNTOWN PLAZA",
                "int_ext": "exterior",
                "time_of_day": "day",
                "description": "Kai transmits a public broadcast to the machine grid promising human liberation, puts on dark glasses, and takes flight.",
                "characters": ["KAI"],
                "props": ["Terminal Kiosk", "Black Duster Coat", "Glasses"],
                "vfx_required": True,
                "stunts_required": True,
                "extras_count": 30,
                "estimated_shoot_hours": 6.0,
                "page_count": 1.5,
                "mood": "triumphant",
                "complexity_score": 7
            }
        ],
        "characters": [
            {"name": "KAI", "description": "The Awakened Cybernetist / The Anomaly", "scene_appearances": [2, 3, 4, 5, 6, 7, 8, 9, 11, 12], "total_scenes": 10, "is_lead": True, "estimated_cost_per_day": 20000},
            {"name": "VALERIE", "description": "Rebel Navigator and Master Infiltrator", "scene_appearances": [1, 5, 7, 8, 10, 11], "total_scenes": 6, "is_lead": True, "estimated_cost_per_day": 12000},
            {"name": "ORION", "description": "Commander of the Hover-Ship Horizon", "scene_appearances": [3, 5, 6, 10], "total_scenes": 4, "is_lead": True, "estimated_cost_per_day": 15000},
            {"name": "AGENT CIPHER", "description": "Sentient System Enforcer Program", "scene_appearances": [1, 3, 4, 7, 9, 11], "total_scenes": 6, "is_lead": True, "estimated_cost_per_day": 14000},
            {"name": "OPERATOR JAX", "description": "Natural-Born Signals Operator", "scene_appearances": [6, 10], "total_scenes": 2, "is_lead": False, "estimated_cost_per_day": 4000}
        ],
        "locations": [
            {"name": "GOVERNMENT ATRIUM", "scene_count": 1, "int_ext": "interior", "time_of_day": "day", "estimated_shoot_days": 4.0, "complexity_score": 10, "permit_required": False},
            {"name": "DOJO SIMULATION", "scene_count": 1, "int_ext": "interior", "time_of_day": "day", "estimated_shoot_days": 5.0, "complexity_score": 10, "permit_required": False},
            {"name": "SUBWAY PLATFORM", "scene_count": 1, "int_ext": "interior", "time_of_day": "night", "estimated_shoot_days": 4.0, "complexity_score": 9, "permit_required": True},
            {"name": "ROOFTOP HELIPAD", "scene_count": 1, "int_ext": "exterior", "time_of_day": "day", "estimated_shoot_days": 3.5, "complexity_score": 10, "permit_required": True}
        ],
        "budget_items": [
            {"category": "Visual Effects (VFX)", "item_name": "Bullet-Time 120-Camera Array Rigs", "quantity": 1, "unit_cost_usd": 8500000, "total_cost_usd": 8500000, "scene_numbers": [1, 8, 11], "notes": "Circular high-speed trigger rig"},
            {"category": "Stunts & Choreography", "item_name": "Acrobatic Wire Martial Arts Team", "quantity": 30, "unit_cost_usd": 35000, "total_cost_usd": 1050000, "scene_numbers": [1, 6, 7, 8, 9], "notes": "6 months wirework contract"},
            {"category": "Special Effects (SFX)", "item_name": "Lobby Shootout Squibs & Plaster Collapse", "quantity": 1, "unit_cost_usd": 1800000, "total_cost_usd": 1800000, "scene_numbers": [7], "notes": "3000 practical squibs"}
        ],
        "schedule_items": [
            {"day_number": 1, "scene_numbers": [1], "location": "HAVEN HOTEL ROOM 303", "int_ext": "interior", "time_of_day": "night", "estimated_hours": 14.0, "crew_size": 90, "notes": "Bullet-time crane kick setup"},
            {"day_number": 2, "scene_numbers": [2, 3, 4], "location": "OMNICORP & CELL", "int_ext": "interior", "time_of_day": "day", "estimated_hours": 12.0, "crew_size": 65, "notes": "Cubicle chase and probe SFX"},
            {"day_number": 3, "scene_numbers": [5, 6], "location": "DOJO SIMULATION", "int_ext": "interior", "time_of_day": "day", "estimated_hours": 14.0, "crew_size": 80, "notes": "Martial arts wire battle"},
            {"day_number": 4, "scene_numbers": [7], "location": "GOVERNMENT ATRIUM", "int_ext": "interior", "time_of_day": "day", "estimated_hours": 16.0, "crew_size": 130, "notes": "Practical column squib explosions"},
            {"day_number": 5, "scene_numbers": [8], "location": "ROOFTOP HELIPAD", "int_ext": "exterior", "time_of_day": "day", "estimated_hours": 12.0, "crew_size": 110, "notes": "Helicopter & backbend bullet dodge"},
            {"day_number": 6, "scene_numbers": [9], "location": "SUBWAY PLATFORM", "int_ext": "interior", "time_of_day": "night", "estimated_hours": 12.0, "crew_size": 85, "notes": "Hand to hand subway fight"}
        ]
    }
}

# Aliases for backward compatibility
DEMO_PROJECTS["inception"] = DEMO_PROJECTS["mindheist"]
DEMO_PROJECTS["mind_heist"] = DEMO_PROJECTS["mindheist"]
DEMO_PROJECTS["matrix"] = DEMO_PROJECTS["cyberhorizon"]
DEMO_PROJECTS["cyber_horizon"] = DEMO_PROJECTS["cyberhorizon"]


def get_demo_project(project_key: str) -> Dict[str, Any]:
    """Get raw demo project dataset."""
    return DEMO_PROJECTS.get(project_key.lower(), DEMO_PROJECTS["mindheist"])


def get_all_demo_summaries() -> List[Dict[str, Any]]:
    """Return lightweight summaries of all pre-seeded demo projects."""
    summaries = []
    for key in ["mindheist", "cyberhorizon"]:
        p = DEMO_PROJECTS[key]
        summaries.append({
            "key": key,
            "id": p["id"],
            "name": p["name"],
            "script_title": p["script_title"],
            "total_scenes": p["total_scenes"],
            "total_pages": p["total_pages"],
            "estimated_budget_usd": p["estimated_budget_usd"],
            "estimated_shoot_days": p["estimated_shoot_days"],
            "complexity_score": p["complexity_score"],
            "status": p["status"],
            "character_count": len(p["characters"]),
            "location_count": len(p["locations"])
        })
    return summaries
